apiVersion: v1
kind: Service
metadata:
  name: goalkeeper
  namespace: statex-apps
  labels:
    app: goalkeeper
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: goalkeeper
  ports:
    - protocol: TCP
      port: 3392
      targetPort: 3392
      name: http
